version: "3"

services:
  wotbot:
    build: .
    env_file:
      - ./configs/wotbot.env
    depends_on:
      - postgres
      - chromedp

  postgres:
    image: postgres
    ports:
      - 5432:5432

  chromedp:
    image: chromedp/headless-shell
    command: --disable-gpu
    shm_size: '2gb'
    ports:
      - 9222:9222